minecraft_version=26.3
minecraft_dependency=>=26.3- <26.4-
loader_version=0.19.5
java_version=25

fabric_api_version=0.161.0+26.3
dependencies.api.malilib_version=0.30.1
dependencies.api.malilib_version.use_sakura_fork=false
dependencies.api.modmenu_version=21.0.0
litematica_version=maven.modrinth:litematica:0.29.0
